"""added is winner to games

Revision ID: 8c18e6938ff7
Revises: 
Create Date: 2025-04-10 17:19:40.575931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c18e6938ff7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_games_game_id', table_name='games')
    op.drop_table('games')
    op.drop_index('ix_ships_ship_id', table_name='ships')
    op.drop_table('ships')
    op.drop_index('ix_boards_board_id', table_name='boards')
    op.drop_table('boards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('board_id', sa.INTEGER(), server_default=sa.text("nextval('boards_board_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('board_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name='boards_game_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['users.user_id'], name='boards_player_id_fkey'),
    sa.PrimaryKeyConstraint('board_id', name='boards_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_boards_board_id', 'boards', ['board_id'], unique=False)
    op.create_table('ships',
    sa.Column('ship_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ship_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ship_coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ship_hits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.board_id'], name='ships_board_id_fkey'),
    sa.PrimaryKeyConstraint('ship_id', name='ships_pkey')
    )
    op.create_index('ix_ships_ship_id', 'ships', ['ship_id'], unique=False)
    op.create_table('games',
    sa.Column('game_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player1_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('turn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.user_id'], name='games_player1_id_fkey'),
    sa.ForeignKeyConstraint(['player2_id'], ['users.user_id'], name='games_player2_id_fkey'),
    sa.PrimaryKeyConstraint('game_id', name='games_pkey')
    )
    op.create_index('ix_games_game_id', 'games', ['game_id'], unique=False)
    # ### end Alembic commands ###
