"""Add board_status to Board Model

Revision ID: a7a36e6a79cd
Revises: 8c18e6938ff7
Create Date: 2025-04-29 18:54:21.402182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7a36e6a79cd'
down_revision: Union[str, None] = '8c18e6938ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('board_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'board_status')
    # ### end Alembic commands ###
